name: Aggiorna Feed AMP

# Esegue ogni ora
on:
  schedule:
    - cron: '0 * * * *'   # Ogni ora all'inizio dell'ora
  workflow_dispatch:       # Permette anche di farlo partire manualmente

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install rss-parser axios fs

      - name: Generate feed.json
        run: |
          node << 'EOF'
          const Parser = require('rss-parser');
          const fs = require('fs');
          const parser = new Parser();

          (async () => {
            const feed = await parser.parseURL('https://brunorachiele.blogspot.com/feeds/posts/default?alt=rss');
            const items = feed.items.slice(0, 10).map(post => {
              // Trova la prima immagine grande nel contenuto del post
              let thumbnail = null;
              const imgMatch = post['content:encoded']?.match(/<img[^>]+src="([^">]+)"/i);
              if (imgMatch) {
                thumbnail = imgMatch[1];
              }
              return {
                title: post.title,
                link: post.link,
                pubDate: post.pubDate,
                contentSnippet: post.contentSnippet?.replace(/<[^>]*>?/gm, '').substring(0,200) + '...',
                thumbnail: thumbnail
              };
            });

            fs.writeFileSync('feed.json', JSON.stringify({ items }, null, 2));
          })();
          EOF

      - name: Commit and push feed.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add feed.json
          git commit -m "Aggiornamento automatico feed AMP $(date +'%Y-%m-%d %H:%M') || true"
          git push
